# Generated by Django 4.0.4 on 2023-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmenuitem',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='cover_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/menu_items/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/cover_sphoto/'),
        ),
    ]
